[package]
name = "migaloo-paint"
version = "1.0.0"
edition = "2021"
author = "Sen Com"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-schema = "1.5.0"
cosmwasm-std = "1.5.0"
cw-storage-plus = "1.1.0"
serde = "1.0.190"
thiserror = "1.0.50"